name: tv-apk-build-action-dev

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'

jobs:
  # 只打包 Android TV APK
  build-tv-apk:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      # 签出代码
      - uses: actions/checkout@v4
        with:
          ref: dev

      # 设置JAVA环境
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: "gradle"

      # 设置Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          cache: true

      # 更新Flutter的packages
      - name: Restore packages
        run: |
          cd simple_live_tv_app
          flutter pub get

      # TV APK签名设置
      - name: Download Android TV keystore
        id: android_tv_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: keystore_tv.jks
          encodedString: ${{ secrets.TV_KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_tv_keystore.outputs.filePath }}" > simple_live_tv_app/android/key.properties
          echo "storePassword=${{ secrets.TV_STORE_PASSWORD }}" >> simple_live_tv_app/android/key.properties
          echo "keyPassword=${{ secrets.TV_KEY_PASSWORD }}" >> simple_live_tv_app/android/key.properties
          echo "keyAlias=${{ secrets.TV_KEY_ALIAS }}" >> simple_live_tv_app/android/key.properties

      # 针对你的设备优化：只构建 armeabi-v7a 架构
      - name: Build TV APK for Armeabi-v7a
        run: |
          cd simple_live_tv_app
          flutter build apk --release --target-platform=android-arm

      #上传TV APK至Artifacts
      - name: Upload TV APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android_tv_armeabi_v7a
          path: simple_live_tv_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      #完成
      - run: echo "✅ "

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'

jobs:
  # 只打包 Android TV APK
  build-tv-apk:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      # 签出代码
      - uses: actions/checkout@v4
        with:
          ref: dev

      # 设置JAVA环境
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: "gradle"

      # 设置Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          cache: true

      # 更新Flutter的packages
      - name: Restore packages
        run: |
          cd simple_live_tv_app
          flutter pub get

      # TV APK签名设置
      - name: Download Android TV keystore
        id: android_tv_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: keystore_tv.jks
          encodedString: ${{ secrets.TV_KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_tv_keystore.outputs.filePath }}" > simple_live_tv_app/android/key.properties
          echo "storePassword=${{ secrets.TV_STORE_PASSWORD }}" >> simple_live_tv_app/android/key.properties
          echo "keyPassword=${{ secrets.TV_KEY_PASSWORD }}" >> simple_live_tv_app/android/key.properties
          echo "keyAlias=${{ secrets.TV_KEY_ALIAS }}" >> simple_live_tv_app/android/key.properties

      # 针对你的设备优化：只构建 armeabi-v7a 架构
      - name: Build TV APK for Armeabi-v7a
        run: |
          cd simple_live_tv_app
          flutter build apk --release --target-platform=android-arm

      #上传TV APK至Artifacts
      - name: Upload TV APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android_tv_armeabi_v7a
          path: simple_live_tv_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      #完成
      - run: echo "✅ TV APK build status: ${{ job.status }}."
