name: Build Android APK for Armeabi-v7a

on:
  workflow_dispatch: # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 检出你的仓库代码

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: |
          ./gradlew assembleDebug --no-daemon
        env:
          # 可选：如果你需要针对特定架构，可能需要在 gradle.properties 中配置，或者使用脚本修改 build.gradle
          # 通常 Flutter 项目（如果此项目是）的 flutter.build 模式会处理，但需确认项目本身支持 armeabi-v7a
          ORG_GRADLE_PROJECT_archsArm="armeabi-v7a" 

      - name: List APK Files
        run: find . -name "*.apk" -type f

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: simple_live_tv_app
          path: |
            **/*.apk
            !**/test-*.apk
