name: tv-apk-build-arv7

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'

jobs:
  build-tv-apk:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      # 签出代码
      - uses: actions/checkout@v4
        with:
          ref: dev

      # 设置JAVA环境
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: "gradle"

      # 设置Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          cache: true

      # 更新Flutter的packages
      - name: Restore packages
        run: |
          cd simple_live_tv_app
          flutter pub get

      # TV APK签名设置
      - name: Download Android TV keystore
        id: android_tv_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: keystore_tv.jks
          encodedString: ${{ secrets.TV_KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_tv_keystore.outputs.filePath }}" > simple_live_tv_app/android/key.properties
          echo "storePassword=${{ secrets.TV_STORE_PASSWORD }}" >> simple_live_tv_app/android/key.properties
          echo "keyPassword=${{ secrets.TV_KEY_PASSWORD }}" >> simple_live_tv_app/android/key.properties
          echo "keyAlias=${{ secrets.TV_KEY_ALIAS }}" >> simple_live_tv_app/android/key.properties

      # 构建APK
      - name: Build TV APK
        run: |
          cd simple_live_tv_app
          flutter build apk --release --target-platform=android-arm

      # 检查构建输出
      - name: Check build outputs
        run: |
          echo "构建输出目录内容:"
          ls -la simple_live_tv_app/build/app/outputs/flutter-apk/
          echo "APK文件:"
          find simple_live_tv_app/build -name "*.apk" -type f

      # 上传APK文件
      - name: Upload TV APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android_tv_apk
          path: simple_live_tv_app/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error

      #完成
      - run: echo "✅ TV APK build OK ."
